"""The Anthropic Messages protocol.

Anthropic's wire format differs from the OpenAI-compatible one in ways that are
themselves evidence, and this adapter is written to preserve every one of them.

**The system prompt is not a message.** It is a separate top-level ``system``
field. An endpoint that accepts a ``system`` *role* inside ``messages`` is not
running Anthropic's validator.

**Content is always a list of typed blocks**, so a single assistant turn can
carry reasoning, prose and tool calls at once and in a defined order.

**Reasoning blocks carry a cryptographic signature.** Anthropic's documentation
states that the signature exists so the API can verify that a thinking block was
generated by Claude, and that tampering with one produces a 400. That makes
signature round-tripping the single strongest identity check available for the
Claude family: a reseller that does not actually route through Anthropic cannot
produce a block that survives replay. It also means the replay must be built
*exactly* right -- a malformed replay would be rejected by a genuine endpoint
and read as a forgery, which is the worst failure mode this tool has.

**There is no ``seed`` and no ``logprobs``.** Those fields do not exist in this
protocol, so this adapter never sends them of its own accord. The api-surface
probe sends them deliberately through ``extra_body`` precisely to see whether
the endpoint quietly accepts fields a genuine Anthropic endpoint would reject.
"""

from __future__ import annotations

import base64
import json
from typing import Any, ClassVar

from ..errors import UnsupportedCapability
from ..types import (
    ApiFamily,
    ChatRequest,
    ChatResponse,
    ContentPart,
    FinishReason,
    ImagePart,
    Message,
    Role,
    TextPart,
    ThinkingBlock,
    Timing,
    ToolCall,
    ToolSpec,
    Usage,
)
from ._http import HttpResult, raise_for_status
from .base import Adapter, Capabilities, register_adapter

__all__ = ["AnthropicAdapter"]

_STOP_REASONS: dict[str, FinishReason] = {
    "end_turn": FinishReason.STOP,
    "stop_sequence": FinishReason.STOP,
    "max_tokens": FinishReason.LENGTH,
    "model_context_window_exceeded": FinishReason.LENGTH,
    "tool_use": FinishReason.TOOL_CALLS,
    "refusal": FinishReason.REFUSAL,
    "pause_turn": FinishReason.PAUSE_TURN,
}

#: Normalised tool-choice keywords mapped onto Anthropic's own vocabulary.
#: ``required`` is the ecosystem-neutral spelling of what Anthropic calls
#: ``any``; anything not listed here is treated as a tool name.
_TOOL_CHOICE_TYPES: dict[str, str] = {
    "auto": "auto",
    "any": "any",
    "required": "any",
    "none": "none",
}

#: Routes that mean "this endpoint does not implement token counting" rather
#: than "the request was wrong".
_ROUTE_ABSENT = frozenset({404, 405, 501})


@register_adapter
class AnthropicAdapter(Adapter):
    """Adapter for ``POST /v1/messages``."""

    name: ClassVar[str] = "anthropic"
    family: ClassVar[ApiFamily] = ApiFamily.ANTHROPIC
    default_base_url: ClassVar[str] = "https://api.anthropic.com/v1"
    default_auth_scheme: ClassVar[str] = "x-api-key"
    chat_path: ClassVar[str] = "/messages"
    capabilities: ClassVar[Capabilities] = Capabilities(
        # Confirmed two independent ways on 2026-07-26: the request schema has
        # no such fields, and no Anthropic model advertises either parameter in
        # OpenRouter's parameter vocabulary.
        logprobs=False,
        seed=False,
        tools=True,
        vision=True,
        structured_output=True,
        reasoning_effort=True,
        thinking_signature=True,
        count_tokens_endpoint=True,
        list_models_endpoint=True,
        streaming=True,
    )

    #: Value sent in the mandatory ``anthropic-version`` header. Overridable
    #: from ``ProviderConfig.headers``, because asking an endpoint for an older
    #: or bogus API version is a legitimate probe.
    api_version: ClassVar[str] = "2023-06-01"

    #: Separator used when several system messages are folded into the single
    #: ``system`` field. It affects token counts, so it is pinned rather than
    #: left to chance.
    system_separator: ClassVar[str] = "\n\n"

    def _auth_headers(self) -> dict[str, str]:
        headers = super()._auth_headers()
        if not any(key.lower() == "anthropic-version" for key in headers):
            headers["anthropic-version"] = self.api_version
        return headers

    # ------------------------------------------------------------------ request

    def build_payload(self, request: ChatRequest) -> dict[str, Any]:
        """Render a :class:`~llmverify.types.ChatRequest` as a Messages body.

        Optional fields are omitted rather than nulled, and ``extra_body`` is
        merged last and verbatim so that probes can send malformed or foreign
        parameters and observe how the endpoint objects.
        """
        turns, system = self._conversation(request.messages)

        payload: dict[str, Any] = {
            "model": self.config.model,
            "max_tokens": request.max_tokens,
            "messages": turns,
        }
        if system:
            payload["system"] = system

        for key, value in (("temperature", request.temperature), ("top_p", request.top_p)):
            if value is not None:
                payload[key] = value

        if request.stop:
            payload["stop_sequences"] = list(request.stop)

        if request.tools:
            payload["tools"] = [
                {
                    "name": tool.name,
                    "description": tool.description,
                    "input_schema": tool.parameters,
                }
                for tool in request.tools
            ]

        if request.tool_choice is not None:
            kind = _TOOL_CHOICE_TYPES.get(request.tool_choice)
            payload["tool_choice"] = (
                {"type": kind} if kind else {"type": "tool", "name": request.tool_choice}
            )

        # Both reasoning effort and structured output live under ``output_config``
        # as of the API reference read on 2026-07-26; the older top-level
        # ``output_format`` spelling is documented as transitional.
        output_config: dict[str, Any] = {}
        if request.reasoning_effort is not None:
            output_config["effort"] = request.reasoning_effort
        if request.response_schema is not None:
            output_config["format"] = {
                "type": "json_schema",
                "schema": request.response_schema,
            }
        if output_config:
            payload["output_config"] = output_config

        if request.thinking_budget is not None:
            payload["thinking"] = {"type": "enabled", "budget_tokens": request.thinking_budget}

        if request.stream:
            payload["stream"] = True

        # request.seed and request.logprobs are deliberately dropped: the
        # protocol has no such fields, and inventing a spelling for them would
        # destroy the api-surface probe's ability to tell a real Anthropic
        # endpoint (which rejects them) from a translating proxy (which does
        # not). A probe that wants them sent must say so through extra_body.
        payload.update(request.extra_body)
        return payload

    def _conversation(self, messages: tuple[Message, ...]) -> tuple[list[dict[str, Any]], str]:
        """Split messages into Anthropic turns and the top-level system prompt.

        Consecutive turns of the same role are folded together because the API
        requires user and assistant turns to alternate. Folding is also what
        puts several tool results into the single user turn that must answer a
        multi-tool assistant turn.
        """
        turns: list[dict[str, Any]] = []
        system_chunks: list[str] = []

        def add(role: str, blocks: list[dict[str, Any]]) -> None:
            if turns and turns[-1]["role"] == role:
                turns[-1]["content"].extend(blocks)
            else:
                turns.append({"role": role, "content": blocks})

        for message in messages:
            if message.role is Role.SYSTEM:
                text = message.text
                if text:
                    system_chunks.append(text)
            elif message.role is Role.TOOL:
                add("user", [_tool_result_block(message)])
            elif message.role is Role.ASSISTANT:
                add("assistant", _assistant_blocks(message))
            else:
                add("user", _content_blocks(message.content))

        for turn in turns:
            if not turn["content"]:
                # An empty turn is invalid, but so is silently dropping it: a
                # probe that sends one wants to see the endpoint's complaint.
                turn["content"] = [{"type": "text", "text": ""}]

        return turns, self.system_separator.join(system_chunks)

    # ----------------------------------------------------------------- response

    def parse_response(self, result: HttpResult) -> ChatResponse:
        """Normalise a non-streamed message, keeping the body intact in ``raw``.

        ``raw`` is the whole response, so identity-bearing fields that have no
        home in the normalised model -- ``service_tier``, ``inference_geo``,
        ``container`` -- remain available to probes.
        """
        body = result.json if isinstance(result.json, dict) else {}
        text, tool_calls, thinking = _split_blocks(body.get("content"))

        return ChatResponse(
            text=text,
            model_reported=_as_str(body.get("model")),
            # Genuine Anthropic ids are prefixed ``msg_``; the prefix is a cheap
            # family signature, so it is preserved rather than stripped.
            response_id=_as_str(body.get("id")),
            finish_reason=_stop_reason(body.get("stop_reason")),
            usage=_parse_usage(body.get("usage")),
            timing=Timing(total_s=result.total_s, ttft_s=result.ttft_s),
            tool_calls=tool_calls,
            thinking=thinking,
            raw=dict(body),
            http_status=result.status,
            http_headers=dict(result.headers),
            api_family=ApiFamily.ANTHROPIC,
        )

    def parse_stream(self, result: HttpResult) -> ChatResponse:
        """Reassemble a message from its event stream.

        The reconstructed content blocks are written back into ``raw`` in the
        same shape a non-streamed response would have, so a probe can read one
        or the other without caring which transport produced it. Signatures
        arrive as their own ``signature_delta`` frames and must be concatenated
        onto the thinking block they belong to, or replay would fail against a
        genuine endpoint.
        """
        blocks: dict[int, dict[str, Any]] = {}
        order: list[int] = []
        message: dict[str, Any] = {}
        usage: dict[str, Any] = {}
        stop_reason: Any = None
        stop_sequence: Any = None

        for event in result.events:
            kind = event.get("type")
            if kind == "message_start":
                start = event.get("message")
                if isinstance(start, dict):
                    message = dict(start)
                    if isinstance(start.get("usage"), dict):
                        usage.update(start["usage"])
            elif kind == "content_block_start":
                index = _block_index(event, order, starting=True)
                start_block = event.get("content_block")
                blocks[index] = _new_block(start_block if isinstance(start_block, dict) else {})
                if index not in order:
                    order.append(index)
            elif kind == "content_block_delta":
                index = _block_index(event, order)
                block = blocks.setdefault(index, _new_block({}))
                if index not in order:
                    order.append(index)
                _apply_delta(block, event.get("delta"))
            elif kind == "message_delta":
                delta = event.get("delta")
                if isinstance(delta, dict):
                    if delta.get("stop_reason") is not None:
                        stop_reason = delta["stop_reason"]
                    if delta.get("stop_sequence") is not None:
                        stop_sequence = delta["stop_sequence"]
                # Usage on message_delta is cumulative, so the last frame wins.
                if isinstance(event.get("usage"), dict):
                    usage.update(event["usage"])

        content = [_finish_block(blocks[i]) for i in order]
        text, tool_calls, thinking = _split_blocks(content)
        # message_start carries stop_reason: null, so message_delta is the real
        # source; the fallback only matters for a proxy that inverts that.
        final_stop = stop_reason if stop_reason is not None else message.get("stop_reason")

        raw = dict(message)
        raw["content"] = content
        raw["usage"] = usage
        if final_stop is not None:
            raw["stop_reason"] = final_stop
        if stop_sequence is not None:
            raw["stop_sequence"] = stop_sequence
        # Frame count is lost on reassembly, and a proxy that buffers a whole
        # completion into one frame looks nothing like token-by-token streaming.
        raw["_llmverify_stream_chunks"] = len(result.events)

        return ChatResponse(
            text=text,
            model_reported=_as_str(message.get("model")),
            response_id=_as_str(message.get("id")),
            finish_reason=_stop_reason(final_stop),
            usage=_parse_usage(usage),
            timing=Timing(total_s=result.total_s, ttft_s=result.ttft_s),
            tool_calls=tool_calls,
            thinking=thinking,
            raw=raw,
            http_status=result.status,
            http_headers=dict(result.headers),
            api_family=ApiFamily.ANTHROPIC,
        )

    # ----------------------------------------------------------------- optional

    async def count_tokens(
        self,
        messages: tuple[Message, ...],
        tools: tuple[ToolSpec, ...] = (),
        *,
        tool_choice: str | None = None,
    ) -> int:
        """Ask the endpoint how many input tokens these messages cost.

        This is the cleanest tokenizer fingerprint available anywhere: the call
        is free, has its own rate limit, runs the real tokenizer, and removes
        generation from the measurement entirely, so the number is a pure
        function of the prompt and the model's tool-use system prompt.

        ``tool_choice`` is exposed because Anthropic publishes *different*
        system-prompt overheads for auto/none versus any/tool, and the gap
        between the two is a second, independent reading of the same signal.

        The request is kept minimal on purpose -- no effort, no thinking budget
        -- so that the published overhead figures remain comparable.

        Raises :class:`~llmverify.errors.UnsupportedCapability` when the route
        does not exist or the response is not shaped as documented.
        """
        request = ChatRequest(messages=messages, tools=tools, tool_choice=tool_choice)
        payload = self.build_payload(request)
        payload.pop("max_tokens", None)
        payload.pop("stream", None)

        result = await self.http.request(
            "POST", f"{self.chat_path}/count_tokens", json_body=payload
        )
        if result.status in _ROUTE_ABSENT:
            raise UnsupportedCapability(
                f"{self.name} endpoint has no token counting route "
                f"({self.chat_path}/count_tokens returned HTTP {result.status})"
            )
        raise_for_status(result, context=f"{self.name} count tokens")

        body = result.json if isinstance(result.json, dict) else {}
        value = body.get("input_tokens")
        if isinstance(value, bool) or not isinstance(value, int):
            raise UnsupportedCapability(
                f"{self.name} count_tokens returned no integer input_tokens: {result.text[:200]!r}"
            )
        return value


# --------------------------------------------------------------------------- #
# Payload construction
# --------------------------------------------------------------------------- #


def _content_blocks(content: str | tuple[ContentPart, ...]) -> list[dict[str, Any]]:
    """Render message content as Anthropic content blocks."""
    if isinstance(content, str):
        return [{"type": "text", "text": content}] if content else []

    blocks: list[dict[str, Any]] = []
    for part in content:
        if isinstance(part, TextPart):
            if part.text:
                blocks.append({"type": "text", "text": part.text})
        elif isinstance(part, ImagePart):
            blocks.append(
                {
                    "type": "image",
                    "source": {
                        "type": "base64",
                        "media_type": part.media_type,
                        "data": base64.b64encode(part.data).decode("ascii"),
                    },
                }
            )
    return blocks


def _assistant_blocks(message: Message) -> list[dict[str, Any]]:
    """Render an assistant turn: reasoning first, then prose, then tool calls.

    The ordering is not cosmetic. Anthropic requires replayed thinking blocks to
    lead the turn, and a signature is only accepted in the position and form the
    API emitted it, so this function is what makes the thinking-signature probe
    a valid test rather than a source of false accusations.
    """
    blocks: list[dict[str, Any]] = []
    for block in message.thinking:
        if block.redacted:
            # A redacted block's payload is an opaque ``data`` string. It has no
            # dedicated slot on ThinkingBlock, so it is carried in ``text`` and
            # restored here; that keeps replay byte-exact, which is the only
            # thing that matters for it.
            blocks.append({"type": "redacted_thinking", "data": block.text})
        else:
            thinking: dict[str, Any] = {"type": "thinking", "thinking": block.text}
            if block.signature is not None:
                thinking["signature"] = block.signature
            blocks.append(thinking)

    blocks.extend(_content_blocks(message.content))

    for call in message.tool_calls:
        blocks.append(
            {
                "type": "tool_use",
                "id": call.id,
                "name": call.name,
                "input": call.arguments if call.arguments is not None else {},
            }
        )
    return blocks


def _tool_result_block(message: Message) -> dict[str, Any]:
    return {
        "type": "tool_result",
        "tool_use_id": message.tool_call_id or "",
        "content": message.text,
    }


# --------------------------------------------------------------------------- #
# Response parsing
# --------------------------------------------------------------------------- #


def _split_blocks(
    content: Any,
) -> tuple[str, tuple[ToolCall, ...], tuple[ThinkingBlock, ...]]:
    """Fold a content-block list into text, tool calls and reasoning blocks."""
    if not isinstance(content, list):
        return "", (), ()

    chunks: list[str] = []
    calls: list[ToolCall] = []
    thinking: list[ThinkingBlock] = []

    for block in content:
        if not isinstance(block, dict):
            continue
        kind = block.get("type")
        if kind == "text":
            text = block.get("text")
            if isinstance(text, str):
                chunks.append(text)
        elif kind == "tool_use":
            arguments = block.get("input")
            arguments = arguments if isinstance(arguments, dict) else None
            calls.append(
                ToolCall(
                    id=str(block.get("id") or ""),
                    name=str(block.get("name") or ""),
                    arguments_raw=json.dumps(
                        arguments if arguments is not None else block.get("input"),
                        ensure_ascii=False,
                    ),
                    arguments=arguments,
                )
            )
        elif kind == "thinking":
            signature = block.get("signature")
            thinking.append(
                ThinkingBlock(
                    text=block.get("thinking") if isinstance(block.get("thinking"), str) else "",
                    # Preserved verbatim: the whole point of the signature is
                    # that only the issuing endpoint can validate it, so any
                    # normalisation here would be tampering.
                    signature=signature if isinstance(signature, str) else None,
                )
            )
        elif kind == "redacted_thinking":
            data = block.get("data")
            thinking.append(
                ThinkingBlock(text=data if isinstance(data, str) else "", redacted=True)
            )

    return "".join(chunks), tuple(calls), tuple(thinking)


def _parse_usage(value: Any) -> Usage:
    """Map Anthropic's usage object, keeping its shape verbatim in ``raw``.

    The key names are a family signature in themselves: no other protocol
    spells cache accounting ``cache_read_input_tokens`` /
    ``cache_creation_input_tokens``.
    """
    if not isinstance(value, dict):
        return Usage()

    details = value.get("output_tokens_details")
    return Usage(
        input_tokens=_as_int(value.get("input_tokens")),
        output_tokens=_as_int(value.get("output_tokens")),
        reasoning_tokens=(
            _as_int(details.get("thinking_tokens")) if isinstance(details, dict) else None
        ),
        cache_read_tokens=_as_int(value.get("cache_read_input_tokens")),
        cache_write_tokens=_as_int(value.get("cache_creation_input_tokens")),
        raw=dict(value),
    )


def _stop_reason(value: Any) -> FinishReason:
    if not isinstance(value, str):
        return FinishReason.OTHER
    return _STOP_REASONS.get(value.strip().lower(), FinishReason.OTHER)


# --------------------------------------------------------------------------- #
# Stream assembly
# --------------------------------------------------------------------------- #


def _block_index(event: dict[str, Any], order: list[int], *, starting: bool = False) -> int:
    """Index of the content block an event refers to.

    Anthropic always sends ``index``. The fallback matters only for a proxy that
    forgets it, and it has to distinguish the two cases: a block that is opening
    gets a fresh slot, while a delta belongs to the block most recently opened.
    Getting that wrong would collapse a whole stream onto block zero.
    """
    index = event.get("index")
    if not isinstance(index, bool) and isinstance(index, int):
        return index
    if starting:
        return max(order) + 1 if order else 0
    return order[-1] if order else 0


def _new_block(start: dict[str, Any]) -> dict[str, Any]:
    return {
        "type": start.get("type"),
        "id": start.get("id"),
        "name": start.get("name"),
        "data": start.get("data"),
        "input": start.get("input"),
        "text": [start["text"]] if isinstance(start.get("text"), str) and start["text"] else [],
        "thinking": (
            [start["thinking"]]
            if isinstance(start.get("thinking"), str) and start["thinking"]
            else []
        ),
        "signature": (
            [start["signature"]]
            if isinstance(start.get("signature"), str) and start["signature"]
            else []
        ),
        "json": [],
    }


def _apply_delta(block: dict[str, Any], delta: Any) -> None:
    """Fold one ``content_block_delta`` into its accumulator."""
    if not isinstance(delta, dict):
        return
    kind = delta.get("type")
    if kind == "text_delta" and isinstance(delta.get("text"), str):
        block["text"].append(delta["text"])
    elif kind == "thinking_delta" and isinstance(delta.get("thinking"), str):
        block["thinking"].append(delta["thinking"])
    elif kind == "signature_delta" and isinstance(delta.get("signature"), str):
        block["signature"].append(delta["signature"])
    elif kind == "input_json_delta" and isinstance(delta.get("partial_json"), str):
        block["json"].append(delta["partial_json"])


def _finish_block(block: dict[str, Any]) -> dict[str, Any]:
    """Turn an accumulator back into the content block a single response holds."""
    kind = block.get("type")
    if kind == "thinking":
        out: dict[str, Any] = {"type": "thinking", "thinking": "".join(block["thinking"])}
        signature = "".join(block["signature"])
        if signature:
            out["signature"] = signature
        return out
    if kind == "redacted_thinking":
        return {"type": "redacted_thinking", "data": block.get("data") or ""}
    if kind == "tool_use":
        raw_json = "".join(block["json"])
        arguments = block.get("input") if isinstance(block.get("input"), dict) else {}
        if raw_json:
            try:
                parsed = json.loads(raw_json)
            except ValueError:
                # Keeping the unparseable fragment is the honest record: whether
                # a stack emits valid JSON is itself a fingerprint.
                parsed = None
            arguments = parsed if isinstance(parsed, dict) else arguments
        return {
            "type": "tool_use",
            "id": block.get("id") or "",
            "name": block.get("name") or "",
            "input": arguments,
        }
    return {"type": "text", "text": "".join(block["text"])}


# --------------------------------------------------------------------------- #
# Scalars
# --------------------------------------------------------------------------- #


def _as_str(value: Any) -> str | None:
    return value if isinstance(value, str) else None


def _as_int(value: Any) -> int | None:
    if isinstance(value, bool):
        return None
    if isinstance(value, int):
        return value
    if isinstance(value, float) and value.is_integer():
        return int(value)
    return None
