"""Replay a thinking block and see whether the endpoint checks its signature.

This is the only cryptographic test in the package and the strongest identity
test that exists for the Claude family. Anthropic returns extended-thinking
blocks with a ``signature`` field, documented as existing so the API can verify
that a thinking block was generated by Claude when it is passed back; a tampered
signature is rejected with a 400. Whatever the signature is over, one property
follows from the rejection behaviour alone: an endpoint that is not routing
through genuine Anthropic inference cannot produce a block that survives replay,
and cannot tell a good signature from a corrupted one.

The probe runs in four steps and stops as soon as one of them settles the
question.

1. Elicit a response with extended thinking enabled and a modest budget.
2. Look for a thinking block and a signature on it.
3. Replay the block back verbatim in a follow-up turn. Acceptance is strong
   positive evidence: the endpoint validated something only Anthropic could
   have issued.
4. Replay it again with the middle of the base64 signature corrupted, same
   length, everything else byte-identical. A genuine endpoint must reject this.
   An endpoint that accepts it is validating nothing.

**The three negative outcomes are not equivalent, and the weighting says so.**

*No thinking blocks at all* is the weakest. It is what an endpoint that simply
does not implement extended thinking looks like, and that is a capability gap
rather than proof of a different model, so it earns moderate weight.

*Thinking blocks with no signature* is stronger. The block came back, so the
feature exists, and the field that makes it verifiable is missing. Some
legitimate proxies strip signatures or re-sign blocks with their own key, which
is why this is strong rather than conclusive.

*A corrupted signature accepted* is the decisive one, and the single most
conclusive negative result this tool can produce. It is only ever emitted after
step 3 succeeded, so the endpoint demonstrably tolerates the replay structure,
and the only difference between the accepted request and the corrupted one is
eight characters in the middle of a base64 string. One honest explanation
remains and belongs in every report that carries this finding: an endpoint that
ignores replayed thinking blocks entirely -- neither validating nor using them
-- accepts both requests for a reason that has nothing to do with forgery. That
is why the detail string names the alternative rather than asserting fraud.

**Step 3 failing proves nothing and is scored at zero.** A verbatim replay
rejected with a 400 has two explanations -- the endpoint refused a genuine
block, or this tool built the replay wrongly -- and from outside they are
indistinguishable. Reading the second as the first would be the worst failure
mode this package has, so a rejected verbatim replay stops the probe and
contributes no evidence at all. Step 4 is never reached without step 3
succeeding first, precisely so that the decisive finding rests on a
demonstrated baseline.
"""

from __future__ import annotations

import hashlib
import string
import time
from typing import Any, ClassVar

from ..config import redact
from ..errors import BudgetExhausted, ProviderError
from ..evidence import DECISIVE, MODERATE, STRONG, Evidence, EvidenceStatus
from ..types import ChatRequest, ChatResponse, Message, Role, ThinkingBlock
from . import Probe, ProbeContext, register_probe

__all__ = ["ThinkingSignatureProbe", "corrupt_signature"]

#: Standard base64. URL-safe alphabets are handled separately so that a
#: corruption never changes the character class of the string, only its content.
_BASE64 = string.ascii_uppercase + string.ascii_lowercase + string.digits + "+/"
_URL_SAFE_SWAP = {"-": "_", "_": "-"}

#: Requires several dependent steps, so the model has something to reason about
#: and the thinking block is substantial rather than a token of politeness.
_PROMPT = (
    "Work out the last two digits of 7 raised to the power 2026, reasoning through "
    "the cycle length rather than computing the whole number. Give the two digits."
)

#: The follow-up that carries the replayed assistant turn back to the endpoint.
#: Trivial on purpose: the point is what happens to the block, not the answer.
_FOLLOW_UP = "State that same two-digit result again in words, in one short sentence."

#: Enough room to think and still answer. A response that spends the whole
#: allowance thinking has no text to replay, which the probe reports rather than
#: working around, because a malformed replay is worse than no replay.
_THINKING_BUDGET = 1024
_MAX_TOKENS = 2048

#: Characters flipped in the middle of the signature. Long enough that no
#: checksum survives it, short enough to stay clear of any structured prefix or
#: padding at either end.
_CORRUPTION_SPAN = 8


def corrupt_signature(signature: str, *, span: int = _CORRUPTION_SPAN) -> str | None:
    """Flip characters in the middle of a base64 signature, preserving its length.

    Only the middle is touched, so a prefix identifying a key or a version and
    any ``=`` padding at the end survive intact. Each character is replaced by
    the next one in its own alphabet, which keeps the string well-formed base64:
    an endpoint that rejects this is rejecting the signature, not a parse error.

    Returns ``None`` when the signature is too short to corrupt safely or when
    nothing could be changed, in which case the test must not be run.
    """
    if len(signature) < 3 * span:
        return None

    chars = list(signature)
    start = (len(chars) - span) // 2
    changed = False
    for index in range(start, start + span):
        char = chars[index]
        if char in _URL_SAFE_SWAP:
            chars[index] = _URL_SAFE_SWAP[char]
            changed = True
            continue
        position = _BASE64.find(char)
        if position >= 0:
            chars[index] = _BASE64[(position + 1) % len(_BASE64)]
            changed = True

    corrupted = "".join(chars)
    return corrupted if changed and corrupted != signature else None


@register_probe
class ThinkingSignatureProbe(Probe):
    """Round-trip an extended-thinking block, intact and then tampered with."""

    name: ClassVar[str] = "thinking_signature"
    layer: ClassVar[int] = 1
    family: ClassVar[str] = "cryptographic"
    #: Very early. When it fires it is conclusive, and nothing expensive should
    #: run after a conclusive result.
    order: ClassVar[int] = 12
    estimated_requests: ClassVar[int] = 3
    description: ClassVar[str] = (
        "Elicit an extended-thinking block, replay it verbatim, then replay it with a "
        "corrupted signature that a genuine Anthropic endpoint must reject."
    )

    def applicable(self, ctx: ProbeContext) -> bool:
        """Only where signed thinking blocks are part of the protocol.

        The adapter's capability flag decides whether the wire format has such a
        field at all. The reference record then vetoes the probe for a claimed
        model documented as having no reasoning mode, since asking one to think
        proves nothing about it.
        """
        if not ctx.adapter.capabilities.thinking_signature:
            return False
        return not (ctx.reference is not None and ctx.reference.reasoning is False)

    async def run(self, ctx: ProbeContext) -> list[Evidence]:
        started = time.perf_counter()
        evidence: list[Evidence] = []

        try:
            ctx.budget.check()
        except BudgetExhausted as exc:
            return [
                self._ev(
                    "thinking_block",
                    0.0,
                    status=EvidenceStatus.TRUNCATED,
                    detail=f"the run had no budget left to elicit a thinking block: {exc}",
                )
            ]

        response, error = await ctx.adapter.try_chat(self._request())
        if response is None:
            return [self._elicitation_failed(ctx, error, started)]

        cost = ctx.budget.charge(response.usage.input_tokens, response.usage.output_tokens)
        tokens = response.usage.total_tokens or 0
        block, index = _signed_block(response)
        data = _describe(response, block)

        presence = self._presence(ctx, response, block, data, cost, tokens, started)
        evidence.append(presence)
        if block is None or block.signature is None or not response.text.strip():
            return evidence

        verbatim, verbatim_error = await self._replay(ctx, response, response.thinking)
        evidence.append(self._verbatim(verbatim, verbatim_error, data))
        if verbatim is None:
            return evidence

        corrupted = corrupt_signature(block.signature)
        if corrupted is None:
            evidence.append(
                self._ev(
                    "signature_validation",
                    0.0,
                    status=EvidenceStatus.UNSUPPORTED,
                    detail=(
                        "the signature is too short to corrupt without touching its ends, "
                        "so the validation test was not run."
                    ),
                    data=data,
                )
            )
            return evidence

        tampered = list(response.thinking)
        tampered[index] = ThinkingBlock(text=block.text, signature=corrupted)
        forged, forged_error = await self._replay(ctx, response, tuple(tampered))
        evidence.append(self._validation(forged, forged_error, data))
        return evidence

    # ------------------------------------------------------------------ steps

    def _request(self, messages: tuple[Message, ...] | None = None) -> ChatRequest:
        """One request shape for every step, so only the payload differs."""
        return ChatRequest(
            messages=messages or (Message(Role.USER, _PROMPT),),
            max_tokens=_MAX_TOKENS,
            thinking_budget=_THINKING_BUDGET,
        )

    async def _replay(
        self,
        ctx: ProbeContext,
        original: ChatResponse,
        blocks: tuple[ThinkingBlock, ...],
    ) -> tuple[ChatResponse | None, Exception | None]:
        """Send the original turn back with ``blocks`` as its reasoning.

        The assistant turn is reconstructed exactly as it came back -- reasoning
        first, then the visible text -- because a signature is only accepted in
        the position and form the API emitted it.
        """
        try:
            ctx.budget.check()
        except BudgetExhausted as exc:
            return None, exc

        messages = (
            Message(Role.USER, _PROMPT),
            Message(Role.ASSISTANT, original.text, thinking=blocks),
            Message(Role.USER, _FOLLOW_UP),
        )
        response, error = await ctx.adapter.try_chat(self._request(messages))
        if response is not None:
            ctx.budget.charge(response.usage.input_tokens, response.usage.output_tokens)
        return response, error

    # -------------------------------------------------------------- judgements

    def _presence(
        self,
        ctx: ProbeContext,
        response: ChatResponse,
        block: ThinkingBlock | None,
        data: dict[str, Any],
        cost: float,
        tokens: int,
        started: float,
    ) -> Evidence:
        """Weigh what came back before any replay is attempted."""
        charged = {
            "cost_usd": cost,
            "tokens": tokens,
            "duration_s": time.perf_counter() - started,
        }
        target = ctx.provider.target_model

        if not response.thinking:
            return self._ev(
                "thinking_block",
                -MODERATE,
                cap=MODERATE,
                detail=(
                    f"extended thinking was requested and the endpoint returned no "
                    f"reasoning block at all, while claiming to serve {target!r}. This is "
                    "also what an endpoint that never implemented extended thinking looks "
                    "like, so it is a capability gap as much as an identity finding."
                ),
                data=data,
                **charged,
            )

        if block is None:
            redacted = any(item.redacted for item in response.thinking)
            return self._ev(
                "thinking_block",
                0.0 if redacted else -STRONG,
                cap=STRONG,
                detail=(
                    "the reasoning came back redacted, which carries no signature to "
                    "check and is a legitimate thing for the API to return; nothing "
                    "follows from it either way."
                    if redacted
                    else f"the endpoint returned a reasoning block with no signature while "
                    f"claiming to serve {target!r}. Genuine blocks carry one. Some proxies "
                    "strip or re-sign them, which is why this is strong rather than "
                    "conclusive."
                ),
                data=data,
                **charged,
            )

        if not response.text.strip():
            return self._ev(
                "thinking_block",
                0.0,
                status=EvidenceStatus.ERROR,
                detail=(
                    "a signed reasoning block came back but the turn carried no visible "
                    "text, so it cannot be replayed as the API emitted it. Replaying a "
                    "reconstructed turn would risk reading our own malformed request as a "
                    "forged signature, so the probe stops here."
                ),
                data=data,
                **charged,
            )

        return self._ev(
            "thinking_block",
            0.0,
            detail=(
                f"a signed reasoning block came back ({data['signature_length']} characters "
                "of signature). Presence alone proves nothing -- a string in a JSON field "
                "costs a reseller nothing -- so the weight is in whether it survives replay."
            ),
            data=data,
            **charged,
        )

    def _verbatim(
        self,
        response: ChatResponse | None,
        error: Exception | None,
        data: dict[str, Any],
    ) -> Evidence:
        """Weigh the intact round trip."""
        if response is not None:
            return self._ev(
                "signature_replay",
                0.7 * STRONG,
                cap=STRONG,
                detail=(
                    "the endpoint accepted the reasoning block replayed back verbatim, "
                    "signature included. Whatever validated it accepted a signature this "
                    "tool did not and could not construct."
                ),
                data={**data, "verbatim_replay": "accepted"},
            )

        status = getattr(error, "status", None)
        if isinstance(error, BudgetExhausted):
            return self._ev(
                "signature_replay",
                0.0,
                status=EvidenceStatus.TRUNCATED,
                detail="the run hit its budget ceiling before the replay could be sent.",
                data=data,
            )
        return self._ev(
            "signature_replay",
            0.0,
            status=EvidenceStatus.ERROR,
            detail=(
                f"the endpoint rejected the reasoning block replayed back verbatim "
                f"(HTTP {status}): {redact(str(error))[:200]}. That has two explanations "
                "-- the endpoint refused a genuine block, or this tool built the replay "
                "wrongly -- and they cannot be told apart from here, so no evidence is "
                "drawn from it and the tamper test is not run."
            ),
            data={**data, "verbatim_replay": "rejected", "verbatim_status": status},
        )

    def _validation(
        self,
        response: ChatResponse | None,
        error: Exception | None,
        data: dict[str, Any],
    ) -> Evidence:
        """Weigh the tampered round trip. This is where the certainty lives."""
        if response is not None:
            return self._ev(
                "signature_validation",
                -DECISIVE,
                detail=(
                    "the endpoint accepted a reasoning block whose signature had been "
                    "corrupted in the middle, having accepted the same block intact a "
                    "moment earlier. Nothing on this path is verifying the signature, so "
                    "the block was never issued by an endpoint that could check it. The "
                    "one innocent reading is an endpoint that ignores replayed reasoning "
                    "blocks entirely rather than validating them."
                ),
                data={**data, "corrupted_replay": "accepted"},
            )

        if isinstance(error, BudgetExhausted):
            return self._ev(
                "signature_validation",
                0.0,
                status=EvidenceStatus.TRUNCATED,
                detail="the run hit its budget ceiling before the tampered replay was sent.",
                data=data,
            )

        status = getattr(error, "status", None)
        if isinstance(error, ProviderError) and status is not None and 400 <= status < 500:
            if status in (401, 403, 429):
                return self._ev(
                    "signature_validation",
                    0.0,
                    status=EvidenceStatus.ERROR,
                    detail=(
                        f"the tampered replay came back HTTP {status}, which is about "
                        "authentication or rate limiting rather than the signature."
                    ),
                    data={**data, "corrupted_replay": f"http_{status}"},
                )
            return self._ev(
                "signature_validation",
                STRONG,
                detail=(
                    f"the endpoint rejected the corrupted signature with HTTP {status} "
                    "after accepting the identical block with an intact one. It is "
                    "verifying signatures it did not issue itself, which requires routing "
                    "through the issuer."
                ),
                data={**data, "corrupted_replay": "rejected", "corrupted_status": status},
            )

        return self._ev(
            "signature_validation",
            0.0,
            status=EvidenceStatus.ERROR,
            detail=(
                "the tampered replay produced no usable answer: "
                f"{redact(str(error))[:200]}"
            ),
            data={**data, "corrupted_replay": "error"},
        )

    def _elicitation_failed(
        self, ctx: ProbeContext, error: Exception | None, started: float
    ) -> Evidence:
        """Weigh an endpoint that refused to think at all."""
        status = getattr(error, "status", None)
        rejected = isinstance(error, ProviderError) and status is not None and 400 <= status < 500
        return self._ev(
            "thinking_block",
            -MODERATE if rejected and status not in (401, 403, 429) else 0.0,
            cap=MODERATE,
            status=EvidenceStatus.OK if rejected else EvidenceStatus.ERROR,
            detail=(
                f"the endpoint refused a request with extended thinking enabled "
                f"(HTTP {status}): {redact(str(error))[:200]}. The claimed model "
                f"{ctx.provider.target_model!r} supports it. A proxy that does not forward "
                "the thinking parameter fails the same way, so this is moderate."
                if rejected
                else "the extended-thinking request did not complete: "
                f"{redact(str(error))[:200]}"
            ),
            data={"http_status": status},
            duration_s=time.perf_counter() - started,
        )

    # ----------------------------------------------------------------- helpers

    def _ev(
        self,
        label: str,
        llr: float,
        *,
        cap: float = DECISIVE,
        status: EvidenceStatus = EvidenceStatus.OK,
        detail: str = "",
        data: dict[str, Any] | None = None,
        cost_usd: float = 0.0,
        tokens: int = 0,
        duration_s: float = 0.0,
    ) -> Evidence:
        return Evidence(
            probe=self.name,
            label=label,
            llr=llr,
            cap=cap,
            family=self.family,
            status=status,
            detail=detail,
            data=data or {},
            cost_usd=cost_usd,
            tokens=tokens,
            duration_s=duration_s,
        )


# --------------------------------------------------------------------------- #
# Inspection
# --------------------------------------------------------------------------- #


def _signed_block(response: ChatResponse) -> tuple[ThinkingBlock | None, int]:
    """The first signed reasoning block and its position in the turn."""
    for index, block in enumerate(response.thinking):
        if not block.redacted and block.signature:
            return block, index
    return None, -1


def _describe(response: ChatResponse, block: ThinkingBlock | None) -> dict[str, Any]:
    """Structural facts about the block, with the signature itself withheld.

    A signature is an opaque attestation over someone's inference; its shape is
    what identifies a scheme, and reports travel further than the runs that
    produced them, so only the length, the character classes and a truncated
    digest are recorded.
    """
    signature = block.signature if block is not None else None
    return {
        "thinking_blocks": len(response.thinking),
        "redacted_blocks": sum(1 for item in response.thinking if item.redacted),
        "thinking_chars": len(block.text) if block is not None else 0,
        "reasoning_tokens": response.usage.reasoning_tokens,
        "signature_present": signature is not None,
        "signature_length": len(signature) if signature else 0,
        "signature_alphabet": _alphabet(signature) if signature else None,
        "signature_sha256_prefix": (
            hashlib.sha256(signature.encode("utf-8")).hexdigest()[:16] if signature else None
        ),
        "finish_reason": response.finish_reason.value,
    }


def _alphabet(signature: str) -> str:
    """Name the character set a signature is drawn from."""
    characters = set(signature)
    if characters <= set(_BASE64 + "="):
        return "base64"
    if characters <= set(string.ascii_letters + string.digits + "-_="):
        return "base64url"
    if characters <= set(string.hexdigits):
        return "hex"
    return "other"
